version: 2
sources:
   - name: raw # allias de la table
     schema: gz_raw_data #Nom exact du dataset dans BQ
     description: greenwez raw data source
     tables:
         - name: sales # allias de la table
           identifier: raw_gz_sales #Nom exact de la table dans BQ
           description: sales of greewneez / we have one row per product_id found in each order_id
           columns:
             - name: "(orders_id || '-' || pdt_id)"
               description: primary key of the table
               tests:
                 - unique
                 - not_null
         - name: product
           identifier: raw_gz_product
           description: purchase_price by products_id
           columns:
             - name: products_id
               description: primary key of the table
               tests:
                 - unique
                 - not_null 
         - name: ship
           identifier: raw_gz_ship
           description: shipping cost
           columns:
             - name: orders_id
               description: primary key of the table
               tests:
                 - unique
                 - not_null
                 
models:
  - name: int_orders_margin
    description: calcul de le marge
    columns: 
      - name: orders_id
        description : primary key
        tests:
           - unique
           - not_null
  - name: int_orders_operational
    description: calcul de le marge operational
    columns: 
      - name: orders_id
        description : primary key
        tests:
           - unique
           - not_null   
  - name: int_sales_margin
    description: calcul de le marge
    columns: 
      - name: "(orders_id || '-' || products_id)"
        description : primary key
        tests:
           - unique
           - not_null      
  - name: financial_days
    description: rapport daily
    columns: 
      - name: date_date
        description : primary key
        tests:
           - unique
           - not_null      
